export const ApartmentsData = [
  {
    id: 1,
    name: "Barbara's Apartment",
    image: require("./pictures/apartment1.jpg"),
    description: "An old fashion apartment",
    amnety1: "Basketball Court",
    amnety2: "Rooftop Lab",
    amnety3: "Dog house",
    amnety4: "Terrace",
    price: 5000,
    location: "Cupang",
  },
  {
    id: 2,
    name: "Lolita's Apartment",
    image: require("./pictures/apartment2.jpg"),
    description: "An old fashion apartment",
    amnety1: "Wifi",
    amnety2: "Pool",
    amnety3: "Garage",
    amnety4: "Balcony",
    price: 5000,
    location: "Sucat",
  },
  {
    id: 3,
    name: "Juliana's Apartment",
    image: require("./pictures/apartment1.jpg"),
    description: "An old fashion apartment",
    amnety1: "Wifi",
    amnety2: "Pool",
    amnety3: "Garage",
    amnety4: "Balcony",
    price: 2000,
    location: "Sucat",
  },
  {
    id: 4,
    name: "Emily's Apartment",
    image: require("./pictures/apartment1.jpg"),
    description: "An old fashion apartment",
    amnety1: "Wifi",
    amnety2: "Pool",
    amnety3: "Garage",
    amnety4: "Balcony",
    price: 1000,
    location: "Alabang",
  },
  {
    id: 5,
    name: "Germano's Apartment",
    image: require("./pictures/apartment1.jpg"),
    description: "Haunted House",
    amnety1: "Wifi",
    amnety2: "Pool",
    amnety3: "Garage",
    amnety4: "Balcony",
    price: 5500,
    location: "Buli",
  },
];
