export const ApartmentsData = [
  {
    id: 1,
    name: "Ricky's Apartment",
    image: require("./pictures/apartment1.jpg"),
    description: "An old fashion apartment",
    amenity1: "Basketball Court",
    amenity2: "Rooftop Lab",
    amenity3: "Dog house",
    amenity4: "Terrace",
    price: 5000,
    location: "Cupang",
  },
  {
    id: 2,
    name: "Edge's Apartment",
    image: require("./pictures/apartment2.jpg"),
    description: "An old fashion apartment",
    amenity1: "Wifi",
    amenity2: "Pool",
    amenity3: "Garage",
    amenity4: "Balcony",
    price: 5000,
    location: "Sucat",
  },
  {
    id: 3,
    name: "McArthur's Apartment",
    image: require("./pictures/apartment1.jpg"),
    description: "An old fashion apartment",
    amenity1: "Wifi",
    amenity2: "Pool",
    amenity3: "Garage",
    amenity4: "Balcony",
    price: 2000,
    location: "Sucat",
  },
  {
    id: 4,
    name: "Renxi's Apartment",
    image: require("./pictures/apartment1.jpg"),
    description: "An old fashion apartment",
    amenity1: "Wifi",
    amenity2: "Pool",
    amenity3: "Garage",
    amenity4: "Balcony",
    price: 1000,
    location: "Alabang",
  },
  {
    id: 5,
    name: "Germano's Apartment",
    image: require("./pictures/apartment1.jpg"),
    description: "Haunted House",
    amenity1: "Wifi",
    amenity2: "Pool",
    amenity3: "Garage",
    amenity4: "Balcony",
    price: 5500,
    location: "Buli",
  },
];
